# Generated by Django 5.0.4 on 2024-04-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FACILITY_NAME', models.CharField(max_length=100)),
                ('STREET_ADDRESS', models.CharField(max_length=100)),
                ('MAIN_ENTRANCE_LONG', models.FloatField()),
                ('MAIN_ENTRANCE_LAT', models.FloatField()),
            ],
            options={
                'db_table': 'dbo.sfmta_managed_offstreet_parking_20240328',
                'ordering': ['FACILITY_NAME'],
            },
        ),
    ]
