# Generated by Django 5.0.4 on 2024-04-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_parkingfacility_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingfacility',
            options={'managed': False, 'ordering': ['facility_name']},
        ),
    ]
