# Generated by Django 5.0.4 on 2024-04-06 06:50
from django.contrib.gis.geos import Point
from django.db import migrations

def convert_text_to_point(apps, schema_editor):
    MyModel = apps.get_model('server', 'ParkingFacility')
    for instance in MyModel.objects.all():
        # Splitting the text into latitude and longitude
        try:
            lon, lat = float(instance.long), float(instance.lat)
            instance.location_point = Point(lon, lat)
            instance.save()
        except ValueError:
            # Handle cases where conversion might fail
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_parkingfacility_options'),
    ]

    operations = [
        migrations.RunPython(convert_text_to_point),
    ]

